# Generated by Django 4.2.1 on 2023-06-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_rating_options_alter_ratingstar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
    ]
